name: Run Eclass Notif

on:
  workflow_dispatch: 
  schedule:
    - cron: '30 0-12 * * 1-5'

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set up
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'

    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        EMAIL: ${{ secrets.EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}  
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        ECLASS_ID: ${{ secrets.ECLASS_ID }}           
        ECLASS_PASSWORD: ${{ secrets.ECLASS_PASSWORD }}
        
      run: |
        cat <<EOF > user.json
        {
            "email": "$EMAIL",
            "passEmail": "$EMAIL_PASSWORD",
            "recipient": "$RECIPIENT_EMAIL",
            "id": "$ECLASS_ID",
            "password": "$ECLASS_PASSWORD",
            "return_url": "e-class/home/"
        }
        EOF

        python PresensiCek.py

    - name: Commit
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        git config --global user.name "dewaahr"
        git config --global user.email "hermanus.rangga@ti.ukdw.ac.id"
        git add dataPresensi.json
        git commit -m "Auto Update dataPresensi.json from workflow"
        git remote set-url origin https://${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
        git push origin main
