name: Run E-Class Notif

on:
  workflow_dispatch: 
  schedule:
    - cron: '15 0-12 * * 1-5'

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'

    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      env:
        ECLASS_ID: ${{ secrets.ECLASS_ID }}           
        ECLASS_PASSWORD: ${{ secrets.ECLASS_PASSWORD }}
        TOKEN_TELEGRAM: ${{ secrets.TOKEN_TELEGRAM }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        cat <<EOF > user.json
        {
            "id": "$ECLASS_ID",
            "password": "$ECLASS_PASSWORD",
            "return_url": "e-class/home/",
            "token": "$TOKEN_TELEGRAM",
            "chat_id": "$CHAT_ID"
        }
        EOF

        python PresensiCek.py

    - name: Check for changes
      id: check_changes
      run: |
        git diff --quiet dataPresensi.json || echo "changed=true" >> $GITHUB_ENV

    - name: Commit and Push Changes
      if: env.changed == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        git config --global user.name "dewaahr"
        git config --global user.email "hermanus.rangga@ti.ukdw.ac.id"
        git add dataPresensi.json
        git commit -m "Auto Update dataPresensi.json from workflow"
        git remote set-url origin https://${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
        git push origin main
