name: Notif Presensi Eclass

on:
  workflow_dispatch: 
  schedule:
    - cron: '30 0-12 * * 1-5'

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      env:
        EMAIL: ${{ secrets.EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}  
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        ECLASS_ID: ${{ secrets.ECLASS_ID }}           
        ECLASS_PASSWORD: ${{ secrets.ECLASS_PASSWORD }}
        DATA_PRESENSI : ${{secrets.DATA_PRESENSI}}
      run: |
        cat <<EOF > user.json
        {
            "email": "$EMAIL",
            "passEmail": "$EMAIL_PASSWORD",
            "recipient": "$RECIPIENT_EMAIL",
            "id": "$ECLASS_ID",
            "password": "$ECLASS_PASSWORD",
            "return_url": "e-class/home/",
        }
        EOF
        python PresensiCek.py

    - name: Upload Presensi Data as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: dataPresensi
        path: dataPresensi.json
